---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: hello-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
    app.openshift.io/runtime: quarkus
  name: hello-service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: hello-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/managed-by: quarkus
    app.openshift.io/runtime: quarkus
    app.kubernetes.io/name: hello-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: hello-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-service
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.openshift.io/runtime: quarkus
        app.kubernetes.io/name: hello-service
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - image: docker.io/chengkuan/quarkus-hello:1.0.0-native
          imagePullPolicy: Always
          name: hello-service
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%